name: credential
on: 
  push: {branches: main}
  pull_request: {branches: main}

jobs:
  secrets-in-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check credential
        run: |
          echo ${{ secrets.JIRATOKEN }}
          echo ${{ secrets.USER }}
          echo ${{ secrets.SERVER }}
          echo ${{ secrets.ESCALATED_BY }}
        env:
          JIRA_TOKEN: ${{ secrets.JIRATOKEN }}
          USER: ${{ secrets.USER }}
          SERVER: ${{ secrets.SERVER }}
          ESCALATED_BY: ${{ secrets.ESCALATED_BY }}