name: credential
on: 
  push: {branches: main}
  pull_request: {branches: main}

jobs:
  secrets-in-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check credential
        run: |
          echo "JIRA_TOKEN=${{ secrets.JIRATOKEN }}" >> $GITHUB_ENV
          echo "USER=${{ secrets.USER }}" >> $GITHUB_ENV
          echo "SERVER=${{ secrets.SERVER }}" >> $GITHUB_ENV
          echo "ESCALATED_BY=${{ secrets.ESCALATED_BY }}" >> $GITHUB_ENV
        